// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartExample.Data;

#nullable disable

namespace ShoppingCartExample.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20220815001739_UpdateRelations")]
    partial class UpdateRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueIdentifier");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId1")
                        .HasColumnType("int");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueIdentifier");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.OrderLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueIdentifier");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLineItem");
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastPurchased")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueIdentifier");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IBANEZ RG655CBM (COBALT BLUE METALLIC)",
                            LastPurchased = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Persephone",
                            Price = 1599.99m,
                            TimeCreated = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(857),
                            TimeModified = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(924),
                            UniqueIdentifier = "a6ae32d5-1c9e-4e85-b1e0-6ef380ae3a9a"
                        },
                        new
                        {
                            Id = 2,
                            Description = "FENDER STRATOCASTER STANDARD (ARCTIC WHITE)",
                            LastPurchased = new DateTime(2010, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aphrodite",
                            Price = 549.99m,
                            TimeCreated = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(979),
                            TimeModified = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(986),
                            UniqueIdentifier = "72dcf6cc-0999-4939-a13e-ea8265408e8b"
                        },
                        new
                        {
                            Id = 3,
                            Description = "IBANEZ S1070PBZ (CERULEAN BLUE BURST)",
                            LastPurchased = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ceres",
                            Price = 1866.99m,
                            TimeCreated = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(1017),
                            TimeModified = new DateTime(2022, 8, 14, 20, 17, 39, 423, DateTimeKind.Local).AddTicks(1023),
                            UniqueIdentifier = "63b1a019-07c2-4fc3-adb2-1713d5296fe0"
                        });
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.Order", b =>
                {
                    b.HasOne("ShoppingCartExample.Models.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.OrderLineItem", b =>
                {
                    b.HasOne("ShoppingCartExample.Models.Domain.Order", null)
                        .WithMany("OrderLineItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ShoppingCartExample.Models.Domain.Order", b =>
                {
                    b.Navigation("OrderLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
